"""Sandbox submission table

Revision ID: 1d4acd96cba8
Revises: 8f4e9d784e41
Create Date: 2026-04-08 15:49:37.060854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4acd96cba8'
down_revision: Union[str, None] = '8f4e9d784e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandbox_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sandbox_type', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('verdict', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', 'sandbox_type', name='uq_sandbox_submissions_sha256_type')
    )
    op.create_index(op.f('ix_sandbox_submissions_sandbox_type'), 'sandbox_submissions', ['sandbox_type'], unique=False)
    op.create_index(op.f('ix_sandbox_submissions_sha256'), 'sandbox_submissions', ['sha256'], unique=False)
    op.drop_index(op.f('idx_file_collection_collector_loop'), table_name='file_collection', mysql_length={'name': 255})
    op.create_index('idx_file_collection_collector_loop', 'file_collection', ['status', 'name', sa.literal_column('insert_date DESC')], unique=False, mysql_length={'name': 255})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_collection_collector_loop', table_name='file_collection', mysql_length={'name': 255})
    op.create_index(op.f('idx_file_collection_collector_loop'), 'file_collection', ['status', 'name', 'insert_date'], unique=False, mysql_length={'name': 255})
    op.drop_index(op.f('ix_sandbox_submissions_sha256'), table_name='sandbox_submissions')
    op.drop_index(op.f('ix_sandbox_submissions_sandbox_type'), table_name='sandbox_submissions')
    op.drop_table('sandbox_submissions')
    # ### end Alembic commands ###
