"""add observable comments table

Revision ID: 8f4e9d784e41
Revises: 88d97a42fbef
Create Date: 2026-03-26 23:46:42.876912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4e9d784e41'
down_revision: Union[str, None] = '88d97a42fbef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observable_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insert_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('observable_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['observable_id'], ['observables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observable_comments_insert_date'), 'observable_comments', ['insert_date'], unique=False)
    op.create_index(op.f('ix_observable_comments_observable_id'), 'observable_comments', ['observable_id'], unique=False)
    op.create_index(op.f('ix_observable_comments_user_id'), 'observable_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observable_comments_user_id'), table_name='observable_comments')
    op.drop_index(op.f('ix_observable_comments_observable_id'), table_name='observable_comments')
    op.drop_index(op.f('ix_observable_comments_insert_date'), table_name='observable_comments')
    op.drop_table('observable_comments')
    # ### end Alembic commands ###
