"""add detection_points table

Revision ID: 21378106119b
Revises: dbae3bc8cdd5
Create Date: 2026-06-06 15:24:51.843570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21378106119b'
down_revision: Union[str, None] = 'dbae3bc8cdd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('queue', sa.String(length=256), nullable=True),
    sa.Column('signature_uuid', sa.String(length=36), nullable=False),
    sa.Column('signature_version', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('insert_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'content_hash', name='uq_detection_points_alert_content')
    )
    op.create_index('ix_detection_points_signature', 'detection_points', ['signature_uuid', 'signature_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detection_points_signature', table_name='detection_points')
    op.drop_table('detection_points')
    # ### end Alembic commands ###
