"""initial schema

Revision ID: 88d97a42fbef
Revises: 
Create Date: 2026-02-18 19:29:18.663072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d97a42fbef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Skip if tables already exist (pre-Alembic deployment).
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.tables "
        "WHERE table_schema = DATABASE() AND table_name = 'alerts'"
    ))
    if result.scalar() > 0:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_mode_priority',
    sa.Column('analysis_mode', sa.String(length=256), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('analysis_mode')
    )
    op.create_table('auth_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_permission_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=512, collation='ascii_general_ci'), nullable=False),
    sa.Column('minor', sa.String(length=512, collation='ascii_general_ci'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major', 'minor', name='u_perm')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('insert_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comments_insert_date'), 'comments', ['insert_date'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_uuid'), 'comments', ['uuid'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_table('config',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('encrypted_passwords',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('event_prevention_tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('event_remediation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('event_risk_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('event_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('event_vector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('incoming_workload_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locks',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('lock_uuid', sa.String(length=36), nullable=True),
    sa.Column('lock_time', sa.DATETIME(), nullable=False),
    sa.Column('lock_owner', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_uuid_locko_uuid', 'locks', ['uuid', 'lock_uuid'], unique=False)
    op.create_index(op.f('ix_locks_lock_time'), 'locks', ['lock_time'], unique=False)
    op.create_table('malware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_malware_name'), 'malware', ['name'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persistence_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persistence_source_name'), 'persistence_source', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('threat_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('omniscience', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('timezone', sa.String(length=512), nullable=True),
    sa.Column('display_name', sa.String(length=1024), nullable=True),
    sa.Column('queue', sa.String(length=64), server_default=sa.text("'default'"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('apikey_hash', sa.String(length=64), nullable=True),
    sa.Column('apikey_encrypted', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apikey_hash')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('work_distribution_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('location', sa.String(length=1024), nullable=False),
    sa.Column('storage_dir', sa.String(length=512), nullable=False),
    sa.Column('insert_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('tool', sa.String(length=256), nullable=False),
    sa.Column('tool_instance', sa.String(length=1024), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('disposition', sa.String(length=64), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('queue', sa.String(length=64), server_default=sa.text("'default'"), nullable=False),
    sa.Column('disposition_user_id', sa.Integer(), nullable=True),
    sa.Column('disposition_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('archived', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('removal_user_id', sa.Integer(), nullable=True),
    sa.Column('removal_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('detection_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_location', 'alerts', ['location'], unique=False, mysql_length=767)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_company_id'), 'alerts', ['company_id'], unique=False)
    op.create_index(op.f('ix_alerts_disposition'), 'alerts', ['disposition'], unique=False)
    op.create_index(op.f('ix_alerts_disposition_user_id'), 'alerts', ['disposition_user_id'], unique=False)
    op.create_index(op.f('ix_alerts_insert_date'), 'alerts', ['insert_date'], unique=False)
    op.create_index(op.f('ix_alerts_owner_id'), 'alerts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_alerts_queue'), 'alerts', ['queue'], unique=False)
    op.create_index(op.f('ix_alerts_removal_user_id'), 'alerts', ['removal_user_id'], unique=False)
    op.create_table('auth_group_permission',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=512, collation='ascii_general_ci'), nullable=False),
    sa.Column('minor', sa.String(length=512, collation='ascii_general_ci'), nullable=False),
    sa.Column('effect', sa.Enum('ALLOW', 'DENY'), server_default=sa.text("'ALLOW'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'major', 'minor', 'effect', name='u_group_perm')
    )
    op.create_index('i_group_effect', 'auth_group_permission', ['group_id', 'effect'], unique=False)
    op.create_index('i_group_major_minor', 'auth_group_permission', ['group_id', 'major', 'minor'], unique=False)
    op.create_table('auth_group_user',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('auth_user_permission',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=512, collation='ascii_general_ci'), nullable=False),
    sa.Column('minor', sa.String(length=512, collation='ascii_general_ci'), nullable=False),
    sa.Column('effect', sa.Enum('ALLOW', 'DENY'), server_default=sa.text("'ALLOW'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'major', 'minor', 'effect', name='u_user_perm')
    )
    op.create_index('i_user_effect', 'auth_user_permission', ['user_id', 'effect'], unique=False)
    op.create_index('i_user_major_minor', 'auth_user_permission', ['user_id', 'major', 'minor'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('creation_date', sa.DATE(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('vector_id', sa.Integer(), nullable=False),
    sa.Column('risk_level_id', sa.Integer(), nullable=False),
    sa.Column('prevention_tool_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DATETIME(), nullable=True),
    sa.Column('alert_time', sa.DATETIME(), nullable=True),
    sa.Column('ownership_time', sa.DATETIME(), nullable=True),
    sa.Column('disposition_time', sa.DATETIME(), nullable=True),
    sa.Column('contain_time', sa.DATETIME(), nullable=True),
    sa.Column('remediation_time', sa.DATETIME(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prevention_tool_id'], ['event_prevention_tool.id'], ),
    sa.ForeignKeyConstraint(['remediation_id'], ['event_remediation.id'], ),
    sa.ForeignKeyConstraint(['risk_level_id'], ['event_risk_level.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['event_status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['event_type.id'], ),
    sa.ForeignKeyConstraint(['vector_id'], ['event_vector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creation_date', 'name', name='creation_date'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('file_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('insert_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('alert_uuid', sa.String(length=36), nullable=True),
    sa.Column('result', sa.Enum('DELAYED', 'ERROR', 'FAILED', 'SUCCESS', 'CANCELLED', 'HOST_OFFLINE', 'FILE_NOT_FOUND'), nullable=True),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('lock', sa.String(length=36), nullable=True),
    sa.Column('lock_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED'), server_default=sa.text("'NEW'"), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('collected_file_path', sa.String(length=1024), nullable=True),
    sa.Column('collected_file_sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_collection_collector_loop', 'file_collection', ['status', 'name', sa.literal_column('insert_date DESC')], unique=False, mysql_length={'name': 255})
    op.create_index('idx_file_collection_name', 'file_collection', ['name'], unique=False, mysql_length=255)
    op.create_index('idx_file_collection_observable_lookup', 'file_collection', ['name', 'type', 'alert_uuid'], unique=False, mysql_length={'name': 255})
    op.create_index('idx_file_collection_result', 'file_collection', ['result'], unique=False)
    op.create_index('idx_file_collection_type', 'file_collection', ['type'], unique=False)
    op.create_index(op.f('ix_file_collection_alert_uuid'), 'file_collection', ['alert_uuid'], unique=False)
    op.create_index(op.f('ix_file_collection_insert_date'), 'file_collection', ['insert_date'], unique=False)
    op.create_index(op.f('ix_file_collection_status'), 'file_collection', ['status'], unique=False)
    op.create_index(op.f('ix_file_collection_update_time'), 'file_collection', ['update_time'], unique=False)
    op.create_table('incoming_workload',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=256), nullable=False),
    sa.Column('work', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['incoming_workload_type.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('malware_threat_mapping',
    sa.Column('malware_id', sa.Integer(), nullable=False),
    sa.Column('threat_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_type_id'], ['threat_type.id'], ),
    sa.PrimaryKeyConstraint('malware_id', 'threat_type_id')
    )
    op.create_table('message_routing',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('route', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=256), nullable=False),
    sa.Column('lock', sa.String(length=36), nullable=True),
    sa.Column('lock_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_routing_mrd', 'message_routing', ['message_id', 'route', 'destination'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('location', sa.String(length=1024), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DATETIME(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('any_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('node_UNIQUE', 'nodes', ['name'], unique=True, mysql_length=767)
    op.create_table('observables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.VARBINARY(length=32), nullable=False),
    sa.Column('value', sa.BLOB(), nullable=False),
    sa.Column('for_detection', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_on', sa.DateTime(), nullable=True),
    sa.Column('fa_hits', sa.Integer(), nullable=True),
    sa.Column('enabled_by', sa.Integer(), nullable=True),
    sa.Column('detection_context', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['enabled_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'sha256', name='i_type_sha256')
    )
    op.create_index('i_obs_sha256', 'observables', ['sha256'], unique=False)
    op.create_index('i_obs_type', 'observables', ['type'], unique=False)
    op.create_index('i_obs_value', 'observables', ['value'], unique=False, mysql_length=767)
    op.create_index(op.f('ix_observables_batch_id'), 'observables', ['batch_id'], unique=False)
    op.create_table('persistence',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('permanent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('uuid', sa.String(length=512), nullable=False),
    sa.Column('value', sa.BLOB(), nullable=True),
    sa.Column('last_update', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['persistence_source.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'uuid', name='idx_p_lookup')
    )
    op.create_index('idx_p_cleanup', 'persistence', ['permanent', 'last_update'], unique=False)
    op.create_index('idx_p_clear_expired_1', 'persistence', ['source_id', 'permanent', 'created_at'], unique=False)
    op.create_index('idx_p_clear_expired_2', 'persistence', ['source_id', 'permanent', 'last_update'], unique=False)
    op.create_table('remediation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('action', sa.Enum('remove', 'restore'), server_default=sa.text("'remove'"), nullable=False),
    sa.Column('insert_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('restore_key', sa.Text(), nullable=True),
    sa.Column('result', sa.Enum('DELAYED', 'ERROR', 'FAILED', 'IGNORE', 'SUCCESS', 'CANCELLED'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('lock', sa.String(length=36), nullable=True),
    sa.Column('lock_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED'), server_default=sa.text("'NEW'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_user_id'), 'remediation', ['user_id'], unique=False)
    op.create_table('company_mapping',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'company_id')
    )
    op.create_table('delayed_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('observable_uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('analysis_module', sa.String(length=512), nullable=False),
    sa.Column('insert_date', sa.DATETIME(), nullable=False),
    sa.Column('delayed_until', sa.DATETIME(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('storage_dir', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_node_delayed_until', 'delayed_analysis', ['node_id', 'delayed_until'], unique=False)
    op.create_index(op.f('ix_delayed_analysis_node_id'), 'delayed_analysis', ['node_id'], unique=False)
    op.create_index(op.f('ix_delayed_analysis_uuid'), 'delayed_analysis', ['uuid'], unique=False)
    op.create_table('event_mapping',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'alert_id')
    )
    op.create_table('event_tag_mapping',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'event_id')
    )
    op.create_table('file_collection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_collection_id', sa.Integer(), nullable=False),
    sa.Column('insert_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('result', sa.Enum('DELAYED', 'ERROR', 'FAILED', 'SUCCESS', 'CANCELLED', 'HOST_OFFLINE', 'FILE_NOT_FOUND'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED'), nullable=False),
    sa.ForeignKeyConstraint(['file_collection_id'], ['file_collection.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_collection_history_insert_date'), 'file_collection_history', ['insert_date'], unique=False)
    op.create_table('malware_mapping',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('malware_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'malware_id')
    )
    op.create_table('node_modes',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('analysis_mode', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'analysis_mode')
    )
    op.create_table('node_modes_excluded',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('analysis_mode', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'analysis_mode')
    )
    op.create_table('observable_mapping',
    sa.Column('observable_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observable_id'], ['observables.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observable_id', 'alert_id')
    )
    op.create_table('observable_remediation_mapping',
    sa.Column('observable_id', sa.Integer(), nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observable_id'], ['observables.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediation.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observable_id', 'remediation_id')
    )
    op.create_table('observable_tag_index',
    sa.Column('observable_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observable_id'], ['observables.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observable_id', 'tag_id', 'alert_id')
    )
    op.create_table('observable_tag_mapping',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('observable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observable_id'], ['observables.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'observable_id')
    )
    op.create_table('remediation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=False),
    sa.Column('insert_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('result', sa.Enum('DELAYED', 'ERROR', 'FAILED', 'IGNORE', 'SUCCESS', 'CANCELLED'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED'), nullable=False),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediation.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'remediation_id')
    )
    op.create_table('tag_mapping',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'alert_id')
    )
    op.create_table('work_distribution',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('READY', 'COMPLETED', 'ERROR', 'LOCKED'), server_default=sa.text("'READY'"), nullable=False),
    sa.Column('lock_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('lock_uuid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['work_distribution_groups.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['incoming_workload.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'work_id')
    )
    op.create_index('fk_work_status', 'work_distribution', ['work_id', 'status'], unique=False)
    op.create_index(op.f('ix_work_distribution_work_id'), 'work_distribution', ['work_id'], unique=False)
    op.create_table('workload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('analysis_mode', sa.String(length=256), nullable=False),
    sa.Column('insert_date', sa.DATETIME(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('storage_dir', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', 'analysis_mode', name='uuid_UNIQUE')
    )
    op.create_index(op.f('ix_workload_analysis_mode'), 'workload', ['analysis_mode'], unique=False)
    op.create_index(op.f('ix_workload_node_id'), 'workload', ['node_id'], unique=False)
    op.create_index(op.f('ix_workload_uuid'), 'workload', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workload_uuid'), table_name='workload')
    op.drop_index(op.f('ix_workload_node_id'), table_name='workload')
    op.drop_index(op.f('ix_workload_analysis_mode'), table_name='workload')
    op.drop_table('workload')
    op.drop_index(op.f('ix_work_distribution_work_id'), table_name='work_distribution')
    op.drop_index('fk_work_status', table_name='work_distribution')
    op.drop_table('work_distribution')
    op.drop_table('tag_mapping')
    op.drop_table('remediation_history')
    op.drop_table('observable_tag_mapping')
    op.drop_table('observable_tag_index')
    op.drop_table('observable_remediation_mapping')
    op.drop_table('observable_mapping')
    op.drop_table('node_modes_excluded')
    op.drop_table('node_modes')
    op.drop_table('malware_mapping')
    op.drop_index(op.f('ix_file_collection_history_insert_date'), table_name='file_collection_history')
    op.drop_table('file_collection_history')
    op.drop_table('event_tag_mapping')
    op.drop_table('event_mapping')
    op.drop_index(op.f('ix_delayed_analysis_uuid'), table_name='delayed_analysis')
    op.drop_index(op.f('ix_delayed_analysis_node_id'), table_name='delayed_analysis')
    op.drop_index('idx_node_delayed_until', table_name='delayed_analysis')
    op.drop_table('delayed_analysis')
    op.drop_table('company_mapping')
    op.drop_index(op.f('ix_remediation_user_id'), table_name='remediation')
    op.drop_table('remediation')
    op.drop_index('idx_p_clear_expired_2', table_name='persistence')
    op.drop_index('idx_p_clear_expired_1', table_name='persistence')
    op.drop_index('idx_p_cleanup', table_name='persistence')
    op.drop_table('persistence')
    op.drop_index(op.f('ix_observables_batch_id'), table_name='observables')
    op.drop_index('i_obs_value', table_name='observables', mysql_length=767)
    op.drop_index('i_obs_type', table_name='observables')
    op.drop_index('i_obs_sha256', table_name='observables')
    op.drop_table('observables')
    op.drop_index('node_UNIQUE', table_name='nodes', mysql_length=767)
    op.drop_table('nodes')
    op.drop_index('idx_message_routing_mrd', table_name='message_routing')
    op.drop_table('message_routing')
    op.drop_table('malware_threat_mapping')
    op.drop_table('incoming_workload')
    op.drop_index(op.f('ix_file_collection_update_time'), table_name='file_collection')
    op.drop_index(op.f('ix_file_collection_status'), table_name='file_collection')
    op.drop_index(op.f('ix_file_collection_insert_date'), table_name='file_collection')
    op.drop_index(op.f('ix_file_collection_alert_uuid'), table_name='file_collection')
    op.drop_index('idx_file_collection_type', table_name='file_collection')
    op.drop_index('idx_file_collection_result', table_name='file_collection')
    op.drop_index('idx_file_collection_observable_lookup', table_name='file_collection', mysql_length={'name': 255})
    op.drop_index('idx_file_collection_name', table_name='file_collection', mysql_length=255)
    op.drop_index('idx_file_collection_collector_loop', table_name='file_collection', mysql_length={'name': 255})
    op.drop_table('file_collection')
    op.drop_table('events')
    op.drop_index('i_user_major_minor', table_name='auth_user_permission')
    op.drop_index('i_user_effect', table_name='auth_user_permission')
    op.drop_table('auth_user_permission')
    op.drop_table('auth_group_user')
    op.drop_index('i_group_major_minor', table_name='auth_group_permission')
    op.drop_index('i_group_effect', table_name='auth_group_permission')
    op.drop_table('auth_group_permission')
    op.drop_index(op.f('ix_alerts_removal_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_queue'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_owner_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_insert_date'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_disposition_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_disposition'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_company_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index('idx_location', table_name='alerts', mysql_length=767)
    op.drop_table('alerts')
    op.drop_table('work_distribution_groups')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('threat_type')
    op.drop_table('tags')
    op.drop_index(op.f('ix_persistence_source_name'), table_name='persistence_source')
    op.drop_table('persistence_source')
    op.drop_table('messages')
    op.drop_index(op.f('ix_malware_name'), table_name='malware')
    op.drop_table('malware')
    op.drop_index(op.f('ix_locks_lock_time'), table_name='locks')
    op.drop_index('idx_uuid_locko_uuid', table_name='locks')
    op.drop_table('locks')
    op.drop_table('incoming_workload_type')
    op.drop_table('event_vector')
    op.drop_table('event_type')
    op.drop_table('event_status')
    op.drop_table('event_risk_level')
    op.drop_table('event_remediation')
    op.drop_table('event_prevention_tool')
    op.drop_table('encrypted_passwords')
    op.drop_table('config')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_comments_uuid'), table_name='comments')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_insert_date'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_table('auth_permission_catalog')
    op.drop_table('auth_group')
    op.drop_table('analysis_mode_priority')
    # ### end Alembic commands ###
