ARG DOCKER_IN_DOCKER_IMAGE=docker:dind
FROM ${DOCKER_IN_DOCKER_IMAGE}

RUN apk update && apk add --no-cache python3 libmagic

RUN python3 -m venv /opt/venv
RUN /opt/venv/bin/pip install -U pip
COPY phishkit/requirements.txt /opt/app/phishkit/
RUN /opt/venv/bin/pip install -r /opt/app/phishkit/requirements.txt
COPY phishkit/phishkit.py phishkit/scanner.py /opt/app/phishkit/
COPY phishkit/Dockerfile.phishkit /opt/app/phishkit/Dockerfile

RUN mkdir -p /output

WORKDIR /opt/app
CMD ["/opt/venv/bin/celery", "-A", "phishkit.phishkit", "worker", "--loglevel", "INFO"]