ARG UBUNTU_DOCKER_IMAGE=ubuntu:22.04
FROM ${UBUNTU_DOCKER_IMAGE}

# env vars
ENV DEBIAN_FRONTEND=noninteractive

# install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libgbm1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libgtk-4-1 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libvulkan1 \
    libx11-6 \
    libxcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    wget \
    xdg-utils \
    python3.10-venv \
    xvfb \
    python3-tk \
    python3-dev \
    zsh \
    git \
    ffmpeg \
    gnome-screenshot

# install google chrome (architecture-aware)
RUN ARCH=$(dpkg --print-architecture) && \
    curl -k -L "https://dl.google.com/linux/direct/google-chrome-stable_current_${ARCH}.deb" -o /tmp/google-chrome-stable.deb && \
    dpkg -i /tmp/google-chrome-stable.deb || apt-get install -f -y && \
    rm /tmp/google-chrome-stable.deb

# install python venv
RUN python3 -m venv /opt/venv

COPY phishkit/requirements.phishkit.txt /opt/app/requirements.txt

# install dependencies
RUN /opt/venv/bin/pip install -U pip \
    && /opt/venv/bin/pip install -r /opt/app/requirements.txt

RUN /opt/venv/bin/seleniumbase install chromedriver

RUN mkdir /export
COPY phishkit/scanner.py /opt/app/scanner.py
COPY etc/phishkit_config.yaml /opt/app/phishkit_config.yaml

VOLUME ["/export"]

WORKDIR /opt/app