jobs:
  - name: daily maintenance
    command: /opt/ace/bin/daily-maintenance.sh >> /opt/ace/data/logs/daily-maintenance-`date '+%Y-%m-%d'`.log 2>&1
    shell: /bin/bash
    schedule: "0 5 * * *"
    concurrencyPolicy: Forbid
  - name: weekly maintenance
    command: /opt/ace/bin/weekly-maintenance.sh >> /opt/ace/data/logs/weekly-maintenance-`date '+%Y-%m-%d'`.log 2>&1
    shell: /bin/bash
    schedule: "0 5 * * 1"
    concurrencyPolicy: Forbid
  - name: update for detection observable cache
    command: /opt/ace/bin/update-for-detection-observable-cache >> /opt/ace/data/logs/update-for-detection-observable-cache-`date '+%Y-%m-%d'`.log 2>&1
    shell: /bin/bash
    schedule: "* * * * *"
    concurrencyPolicy: Forbid
  - name: refresh newly registered domains
    command: /opt/ace/bin/nrd-refresh >> /opt/ace/data/logs/nrd-refresh-`date '+%Y-%m-%d'`.log 2>&1
    shell: /bin/bash
    schedule: "*/30 * * * *"
  - name: analysis cache partition maintenance
    command: /opt/ace/bin/manage-analysis-result-cache-partitions.sh >> /opt/ace/data/logs/analysis-cache-partitions-`date '+%Y-%m-%d'`.log 2>&1
    shell: /bin/bash
    schedule: "0 4 * * *"
    concurrencyPolicy: Forbid
  - name: analysis cache stats
    command: /opt/ace/bin/analysis-cache-stats >> /opt/ace/data/logs/analysis-cache-stats-`date '+%Y-%m-%d'`.log 2>&1
    shell: /bin/bash
    schedule: "*/15 * * * *"
    concurrencyPolicy: Forbid
  - name: analysis cache gc (durable blobs)
    command: /opt/ace/bin/analysis-cache-gc >> /opt/ace/data/logs/analysis-cache-gc-`date '+%Y-%m-%d'`.log 2>&1
    shell: /bin/bash
    schedule: "0 * * * *"
    concurrencyPolicy: Forbid
  - name: analysis cache local maintenance
    command: /opt/ace/bin/analysis-cache-local-maintenance >> /opt/ace/data/logs/analysis-cache-local-maintenance-`date '+%Y-%m-%d'`.log 2>&1
    shell: /bin/bash
    schedule: "*/15 * * * *"
    concurrencyPolicy: Forbid