import os
import uuid

import pytest

from saq.analysis.analysis import Analysis
from saq.constants import F_FILE, F_FQDN, F_TEST, F_URL
from saq.environment import get_base_dir
from tests.saq.helpers import create_root_analysis


class DeletableAnalysis(Analysis):
    pass


class FirstAnalysis(Analysis):
    pass


class SecondAnalysis(Analysis):
    pass


def _detail_path(root, analysis):
    return os.path.join(get_base_dir(), root.storage_dir, ".ace", analysis.external_details_path)


@pytest.mark.integration
def test_delete_analysis_removes_node_detail_file_child_and_detections():
    """deleting an analysis removes it from the observable, deletes its external detail
    file, prunes the orphaned observable it generated, and drops the in-tree detections."""
    root = create_root_analysis(uuid=str(uuid.uuid4()))
    root.initialize_storage()

    obs = root.add_observable_by_spec(F_FQDN, "evil.example.com")
    analysis = DeletableAnalysis()
    obs.add_analysis(analysis)
    analysis.details = {"k": "v"}

    child = analysis.add_observable_by_spec(F_URL, "https://evil.example.com/clicked")
    child.add_detection_point("someone clicked")
    analysis.add_detection_point("clicker provider hit")

    root.save()

    detail_path = _detail_path(root, analysis)
    registry = root.analysis_tree_manager.observable_registry
    assert os.path.exists(detail_path)
    assert child.uuid in registry
    assert len(root.all_detection_points) == 2

    obs.delete_analysis(analysis)

    assert obs.get_analysis(DeletableAnalysis) is None
    assert not os.path.exists(detail_path)
    assert child.uuid not in registry
    assert root.all_detection_points == []


@pytest.mark.integration
def test_delete_analysis_keeps_child_referenced_by_other_analysis():
    """an observable generated by the deleted analysis is retained when another analysis
    still references it."""
    root = create_root_analysis(uuid=str(uuid.uuid4()))
    root.initialize_storage()

    obs = root.add_observable_by_spec(F_FQDN, "evil.example.com")

    first = FirstAnalysis()
    obs.add_analysis(first)
    shared = first.add_observable_by_spec(F_URL, "https://shared.example.com/")

    second = SecondAnalysis()
    obs.add_analysis(second)
    second.add_observable(shared)  # the same observable is referenced by a second analysis

    root.save()

    registry = root.analysis_tree_manager.observable_registry
    assert shared.uuid in registry

    obs.delete_analysis(first)

    assert obs.get_analysis(FirstAnalysis) is None
    assert obs.get_analysis(SecondAnalysis) is second
    # shared is still referenced by SecondAnalysis, so it must survive
    assert shared.uuid in registry
    assert second.has_observable(shared)


@pytest.mark.integration
def test_delete_analysis_keeps_original_alert_observable():
    """observables that came with the original alert are never removed, even when the
    deleted analysis was the only thing referencing them."""
    root = create_root_analysis(uuid=str(uuid.uuid4()))
    root.initialize_storage()

    original = root.add_observable_by_spec(F_FQDN, "evil.example.com")
    host = root.add_observable_by_spec(F_TEST, "host")

    analysis = DeletableAnalysis()
    host.add_analysis(analysis)
    analysis.add_observable(original)

    root.save()

    registry = root.analysis_tree_manager.observable_registry
    obs_count = len(registry)

    host.delete_analysis(analysis)

    assert host.get_analysis(DeletableAnalysis) is None
    assert original.uuid in registry
    # only the analysis was removed; both original observables remain
    assert len(registry) == obs_count


@pytest.mark.integration
def test_delete_analysis_deletes_backing_file_of_generated_file_observable(tmpdir):
    """a file observable generated by the deleted analysis has its backing file removed."""
    from saq.observables.file import FileObservable

    root = create_root_analysis(uuid=str(uuid.uuid4()))
    root.initialize_storage()

    obs = root.add_observable_by_spec(F_FQDN, "evil.example.com")
    analysis = DeletableAnalysis()
    obs.add_analysis(analysis)

    source = tmpdir.join("payload.txt")
    source.write("malware")
    file_obs = analysis.add_file_observable(str(source))
    assert isinstance(file_obs, FileObservable)

    root.save()

    full_path = file_obs.full_path
    registry = root.analysis_tree_manager.observable_registry
    assert os.path.exists(full_path)
    assert file_obs.uuid in registry

    obs.delete_analysis(analysis)

    assert file_obs.uuid not in registry
    assert not os.path.exists(full_path)
