import logging
from typing import TYPE_CHECKING, Any, Callable, Optional

from saq.analysis.base_node import BaseNode
from saq.analysis.module_path import MODULE_PATH
from saq.analysis.pivot_link import PivotLink
from saq.analysis.search import search_down
from saq.analysis.serialize.analysis_serializer import AnalysisSerializer
from saq.analysis.summary_detail import SummaryDetail
from saq.constants import EVENT_ANALYSIS_MARKED_COMPLETED, EVENT_OBSERVABLE_ADDED

if TYPE_CHECKING:
    from saq.analysis.observable import Observable

class Analysis(BaseNode):
    """Represents an output of analysis work."""

    def __init__(self, sort_order: int=100, *args, **kwargs):
        super().__init__(*args, **kwargs)


        # list of Observables generated by this Analysis
        self._observables: list["Observable"] = []

        # a temporary list of Observable UUIDs that will be used to load self._observables
        self.observable_references: list[str] = []

        # represents the instance of the AnalysisModule that generated this Analysis
        # this defaults to None if the module has no defined instances
        self.instance: Optional[str] = None

        # the observable this Analysis is for
        # this is optional because the root node does not have a parent
        self._observable: Optional["Observable"] = None

        # a brief (or brief-ish summary of what the Analysis produced)
        # the idea here is that the analyst can read this summary and get
        # a pretty good idea of what was discovered without needing to
        # load all the details of the alert
        self._summary: Optional[str] = None

        # the list of SummaryDetail objects that have been added
        # these are used to display useful information to the analyst
        self._summary_details: list[SummaryDetail] = []

        # this flag indicates that the analysis has been fully completed
        # this defaults to True (this is important that it defaults to True)
        # in most cases analysis happens once and that's it
        # but in the case of delayed analysis this would be set to False
        # if this is set to True when the engine will not consider it done
        # (see lib/saq/modules/__init__.py accepts())
        self._completed: bool = True

        # this is set to True when we submit this as an alert
        # currently this is really only supported by the Alert class itself
        # but eventually I would like to be able to alert from any Analysis object
        self._alerted: bool = False

        # set to True when delayed analysis is requested
        self._delayed: bool = False

        # a list of external links an analyst can pivot to from this analysis
        self._pivot_links: list[PivotLink] = []

        # the details of the analysis
        # this is a dict that can be used to store any data that is relevant to the analysis
        # NOTE this are not loaded by default when an Analysis is loaded from persistence
        # this must be explicitly loaded by calling load_details()
        self.details: dict = {}

        # where the analysis details are saved
        # if set to None then the analysis details have not been saved yet
        # NOTE this path is relative to the .ace subdirectory of the storage directory
        self.external_details_path: Optional[str] = None

        # the size of the analysis details when saved to disk
        self.details_size: Optional[int] = None

        # this flag indicates that the analysis details have been modified
        # and need to be saved
        self.details_modified = False

        # a list of documents that will be used to generate LLM context
        # each document becomes a vector embedding
        self.llm_context_documents: list[str] = []

    # analysis properties and methods
    # ------------------------------------------------------------------------

    @property
    def whitelisted(self) -> bool:
        return self.has_tag("whitelisted")

    def set_details_modified(self):
        """Calling this function indicates that the details have become modified and thus need to be saved."""
        # this is called automatically when you add an Analysis object to an Observable
        logging.debug(f"setting details modified for {self}")
        self.details_modified = True

    def load_details(self) -> bool:
        """Loads the details of this analysis from disk."""
        return self.analysis_tree_manager.load_analysis_details(self)

    @property
    def question(self) -> Optional[str]:
        """Returns the question this analysis was trying to answer.
           By default this returns the __doc__ by default, or subclasses can override it.
           This result is returned to the analyst when they mouse-over in the GUI."""
        return self.__doc__

    @property
    def pivot_links(self) -> list[PivotLink]:
        return self._pivot_links

    @pivot_links.setter
    def pivot_links(self, value: list[PivotLink]):
        assert all([isinstance(_, PivotLink) for _ in value])
        self._pivot_links = value

    def add_pivot_link(self, url: str, icon: Optional[str]=None, text: Optional[str]=None):
        self._pivot_links.append(PivotLink(url, icon, text))

    @property
    def delayed(self) -> bool:
        return self._delayed

    @delayed.setter
    def delayed(self, value: bool):
        assert isinstance(value, bool)
        self._delayed = value

    @property
    def summary(self) -> Optional[str]:
        return self._summary

    @summary.setter
    def summary(self, value: Optional[str]):
        self._summary = value

    @property
    def summary_details(self) -> list[SummaryDetail]:
        """Returns a list of SummaryDetail objects that represent the summaries of analysis performed."""
        return self._summary_details

    @summary_details.setter
    def summary_details(self, value: list[SummaryDetail]):
        self._summary_details = value

    def add_summary_detail(self, *args, **kwargs):
        self.summary_details.append(SummaryDetail(*args, **kwargs))

    @property
    def completed(self) -> bool:
        return self._completed

    @completed.setter
    def completed(self, value: bool):
        assert isinstance(value, bool)

        # if this state is changing from False to True then we want to fire an event
        # so that the engine can pick this up and continue analysis
        # this is because most analysis triggers off of adding Analysis objects to Observables
        # but in the case of delayed analysis the Analysis has already been added and we're just waiting for results
        # once that delayed analysis is completed we want to allow other modules a chance to look at it
        _trigger_event = False
        if not self._completed and value:
            _trigger_event = True

        self._completed = value

        if _trigger_event:
            logging.debug(f"{self} has marked as completed manually (fire event)")
            self.fire_event(EVENT_ANALYSIS_MARKED_COMPLETED)

    @property
    def module_path(self) -> str:
        """Returns module.path:class_name[:instance]."""
        return MODULE_PATH(self)

    def is_on_detection_path(self) -> bool:
        """Returns True if this node or any node down to (but not including) the root has a detection point."""
        from saq.analysis.root import RootAnalysis
        if self.has_detection_points():
            return True

        return search_down(self, lambda obj: False if isinstance(obj, RootAnalysis) else obj.has_detection_points()) is not None


    # JSON serialization delegation methods
    # ------------------------------------------------------------------------

    @property
    def json(self):
        return AnalysisSerializer.serialize(self)

    @json.setter
    def json(self, value):
        AnalysisSerializer.deserialize(self, value)


    # observables
    # ------------------------------------------------------------------------

    @property
    def observable(self) -> Optional["Observable"]:
        """The Observable this Analysis is for (or None if this is an Alert.)"""
        return self._observable

    @observable.setter
    def observable(self, value: Optional["Observable"]):
        from saq.analysis.observable import Observable
        assert value is None or isinstance(value, Observable)
        self._observable = value

    @property
    def observables(self) -> list["Observable"]:
        """A list of Observables that was generated by this Analysis.  These are references to the Observables to Alert.observables."""
        # at run time this is a list of Observable objects which are references to what it stored in the Alert.observable_store
        # when serialized to JSON this becomes a list of uuids (keys to the Alert.observable_store dict)
        return self._observables

    @observables.setter
    def observables(self, value: list["Observable"]):
        from saq.analysis.observable import Observable
        assert isinstance(value, list)
        assert all(isinstance(o, Observable) for o in self._observables)
        self._observables = value

    def has_observable(self, observable: "Observable") -> bool:
        """Returns True if this Analysis has this Observable."""
        return self.find_observable(lambda o: o == observable) is not None

    def has_observable_by_spec(self, o_type: str, o_value: str) -> bool:
        """Returns True if this Analysis has an Observable with the given type and value."""
        return self.find_observable(lambda o: o.type == o_type and o.value == o_value) is not None

    @property
    def children(self) -> list["Observable"]:
        """Returns what is considered all of the "children" of this object (in this case is the the Observables.)"""
        return self.observables

    def _load_observable_references(self):
        """Utility function to replace uuid strings in Analysis.observables with references to Observable objects in Alert.observable_store."""
        _buffer: list["Observable"] = []
        for observable_id in self.observable_references:
            observable = self.analysis_tree_manager.get_observable_by_id(observable_id)
            if observable is None:
                logging.warning(f"missing observable with uuid {observable_id} in {self.analysis_tree_manager.root_analysis}")
            else:
                _buffer.append(observable)

        self._observables = _buffer

    @property
    def observable_types(self):
        """Returns the list of unique observable types for all Observables generated by this Analysis."""
        return list(set([o.type for o in self.observables]))

    def get_existing_observable(self, observable: "Observable") -> Optional["Observable"]:
        """Returns the Observable object that matches the given Observable object, or None if no match is found."""
        for target_observable in self.observables:
            if target_observable == observable:
                return target_observable

        return None

    def get_observables_by_type(self, o_type: str) -> list["Observable"]:
        """Returns the list of Observables that match the given type."""
        return [o for o in self.observables if o.type == o_type]

    def get_observable_by_type(self, o_type: str) -> Optional["Observable"]:
        """Returns the first Observable of type o_type, or None if no Observable of that type exists."""
        result = self.get_observables_by_type(o_type)
        if len(result) == 0:
            return None

        return result[0]

    def find_observable(self, criteria: Callable[["Observable"], bool]) -> Optional["Observable"]:
        """Returns the first observable that matches the criteria, or None if nothing is found.

           param:criteria Must be one of the following:
           * a callable that takes a single :class:`Observable` as a parameter and returns a boolean
           * an indicator type (str)

           return: the first observable that matches the criteria, or None if nothing is found."""

        result = self.find_observables(criteria)
        if result:
            return result[0]
        else:
            return None

    def find_observables(self, criteria: Callable[["Observable"], bool]) -> list["Observable"]:
        """Same as :meth:`find_observable` but returns all observables found that match the criteria."""
        result: list["Observable"] = []
        for observable in self.observables:
            if criteria(observable):
                result.append(observable)

        return result

    # observable management (public interface)
    # ------------------------------------------------------------------------

    def add_observable(self, observable: "Observable") -> Optional["Observable"]:
        """Adds the Observable to this Analysis.  Returns the Observable object, the one that already existed, or None if per-type limit reached."""
        from saq.analysis.observable import Observable
        assert isinstance(observable, Observable)
        return self.analysis_tree_manager.add_observable(self, observable)

    def add_observable_by_spec(self, o_type: str, o_value, o_time=None, sort_order=100, volatile=False) -> Optional["Observable"]:
        """Adds this observable specified by type, value and time to this Analysis.  
           Returns the new Observable object, or the one that already existed."""
        return self.analysis_tree_manager.add_observable_by_spec(self, o_type, o_value, o_time=o_time, sort_order=sort_order, volatile=volatile)

    def add_file_observable(self, path: Any, target_path: Optional[str]=None, move: Optional[bool]=False, **kwargs):
        from saq.observables.file import FileObservable
        assert target_path is None or isinstance(target_path, str)
        assert isinstance(move, bool)

        try:
            # Use file manager to store the file
            sha256_hash, relative_path = self.file_manager.store_file(path, target_path, move)
            
            # Create and add the file observable
            return self.analysis_tree_manager.add_observable(
                self,
                FileObservable(
                    sha256_hash, 
                    file_path=relative_path,
                    **kwargs))
                    
        except FileNotFoundError:
            logging.warning(f"add_file_observable called to non-existant file: {path}")
            return None
        except Exception as e:
            logging.error(f"unable to add file observable {path}: {e} ({type(e)})")
            raise e

    # LLM context management
    # ------------------------------------------------------------------------

    def add_llm_context_document(self, document: str):
        """Add a document to this analysis."""
        self.llm_context_documents.append(document)

    # observable management (private interface)
    # ------------------------------------------------------------------------

    # this should only be called by the AnalysisTreeManager
    def add_observable_to_tree(self, observable: "Observable"):
        """Modifies the analysis tree to include the given observable."""
        from saq.analysis.observable import Observable
        assert isinstance(observable, Observable)
        self._observables.append(observable)
        self.fire_event(EVENT_OBSERVABLE_ADDED, observable)

    # special methods
    # ------------------------------------------------------------------------

    def __str__(self):
        result = '{}'.format(type(self).__name__)
        if self.instance is not None:
            result += f':{self.instance}'

        return result

    # this is used to sort in the GUI
    def __lt__(self, other):
        if not isinstance(other, Analysis):
            return False

        self_str = self.summary if self.summary is not None and isinstance(self.summary, str) else str(self)
        other_str = other.summary if other.summary is not None and isinstance(other.summary, str) else str(other)

        return self_str < other_str

    def __eq__(self, other):
        if not isinstance(other, Analysis):
            return False

        return self.uuid == other.uuid
        #return self.observable.id == other.observable.id and self.details == other.details and self.summary == other.summary

    def __hash__(self):
        # XXX this is weird -- why are we hashing the summary?
        return hash(self.summary)

    ##########################################################################
    # OVERRIDABLES 

    @property
    def display_name(self) -> str:
        """By default this returns the name of the Analysis class.
        You can override this to return a more human readable name."""
        return type(self).__name__

    def generate_summary(self) -> Optional[str]:
        """Returns a human readable summary of the analysis.  Returns None if the analysis is not to be displayed in the GUI."""
        return None

    def always_visible(self):
        """If this returns True then this Analysis is always visible in the GUI."""
        return False

class UnknownAnalysis(Analysis):
    """Represents an Analysis that cannot be modified.  This is used when an Analysis is serialized to JSON but the class is not found."""

    def __init__(self, module_path, *args, **kwargs):
        self._module_path = module_path
        super().__init__(*args, **kwargs)

    @Analysis.module_path.getter
    def module_path(self):
        return self._module_path

    def save(self):
        pass

    def flush(self):
        pass

    def reset(self):
        pass

    def discard_details(self):
        pass

    def clear_observables(self):
        pass

    def add_observable(self, *args, **kwargs):
        pass

    def _add_observable(self, observable):
        pass

    def _add_observable_by_spec(self, o_type, o_value, o_time=None):
        pass

    def tag_detection(self, source, event, tag):
        pass
